!pip install streamlit
import streamlit as st
!pip install pyngrok

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQ-ELSXj5Nu22_PCE_pbw3fyrLJ3otl4
"""

import streamlit as st

st.title("¡Hola, Streamlit!")
st.write("Esta es una prueba para ver si la app se despliega correctamente.")
